baseURL:
languageCode: 'en-us'
title: 'MotoLogix examples'
themesDir: '../themes'
theme: 'hugo-plc-docs-theme'
author: Yaskawa Europe GmbH
copyright: 'Copyright © 2021 Yaskawa Europe GmbH'

contentDir: 'source'
resourceDir: '_temp/resources/'
publishDir: '_temp/public/'

markup:
  highlight:
    codeFences: false

  goldmark:
    renderer:
      unsafe: true

params:
  supportLink: 'mailto:Software-Download@yaskawa.eu.com'
  navBar:
    wide_logo: true
