baseURL:
languageCode: 'en-us'
title: 'MotoLogix examples'
themesDir: '../themes'
theme: 'hugo-plc-docs-theme'
author: Yaskawa Europe GmbH
copyright: 'Copyright © 2021 Yaskawa Europe GmbH'

contentDir: 'source'
resourceDir: '_temp/resources/'
publishDir: '_temp/public/'

markup:
  highlight:
    codeFences: false

  goldmark:
    renderer:
      unsafe: true

taxonomies:
  category: categories
  tag: tags
  parameter bundle: prmBundles
  controller: controller
  plc: plc
  fieldbus: fieldbus
  board: boards

params:
  supportLink: 'mailto:Software-Download@yaskawa.eu.com'
  navBar:
    wide_logo: true

# special output formats for `setup-robot`:
#  - settings.txt (YEU parameter settings file)
#  - settings.psc (parameter settings script)
# output format creating cleanup files
#  - cleanup.txt (contains file names of superfluous images)
mediaTypes:
  text/parameter-settings:
    suffixes:
      - txt
  text/parameter-script:
    suffixes:
      - psc
  text/cleanup:
    suffixes:
      - txt

outputFormats:
  PRM:
    baseName: settings
    isPlainText: true
    mediaType: text/parameter-settings
  PSC:
    baseName: settings
    isPlainText: true
    mediaType: text/parameter-script
  cleanup:
    baseName: cleanup
    isPlainText: true
    mediaType: text/cleanup
outputs:
  page:
    - HTML
    - cleanup
  home:
    - HTML
  section:
    - HTML
  taxonomy:
    - HTML
  term:
    - HTML

enableRobotsTXT: true
enableGitInfo: true
enableEmoji : true