name: "⭐ Feature or enhancement request"
description: Propose something new.
title: "[Feature Request]: "
body:
  - type: input
    id: lib_item_name
    attributes:
      label: Lib item name
      description: Please provide the name of the library item.
      placeholder: "e.g. `McePosTable`"
    validations:
      required: true

  - type: input
    id: lib_item_version
    attributes:
      label: Lib item version
      description: Please provide the version of the library item. This is usually found in the header of the code.
      placeholder: "e.g. `0.7.0`"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Description of the new feature / enhancement
      placeholder: What is the expected behavior of the proposed feature?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Scenario when this would be used?
      placeholder: What is the scenario this would be used?
    validations:
      required: true

  - type: markdown
    attributes:
      value: Please limit one request per issue.
